project:
  type: website
  output-dir: docs

website:
  title: "StratoBayes Workshop"
  page-navigation: false
  sidebar:
    style: "docked"
    search: true
    logo: "images/logo-2.png"
    contents:
      - index.qmd
      # - section: "Content"
        # contents:
        #   - day1.qmd
        #   - day2.qmd
        #   - day3.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

